### ISSUE TITLE
A crashing PDF file

### ISSUE THREAD

**Issue by coooooooorey** [amkhlv/pdfviewer#2]
this is the crashing file.

https://drive.google.com/file/d/0BxUO3KDi7ZfyZjUxLVJnRUliMnM/view?usp=sharing

I did some debug. here is the location:

> PageItem.cpp 
> ->
> static QList<Link> getLinks(Poppler::Page\* popplerPage, const QStringList &popplerPageLabels) 
> ->
> link.pageLabel = popplerPageLabels.at(int(link.pageNumber));

the result of  `int(link.pageNumber)`   is -1.

I don't know how to fix it.
please help

**Comment by amkhlv** [comment]
Hi ! Thank you for pointing this out. I am very busy now; I tried to
look at the code but also could not figure out how it works. (99% of the
code is not mine) I will look more.

Meanwhile, please, if you have time, check it with pdq4:

https://github.com/amkhlv/pdq4

This is supposed to be a lightweight version rewritten from scratch,
I understand it much better. I mean, it crashes for many reasons at this
moment, but would it crash on your particular case?
Andrei

Em Dom, 2016-02-28 às 02:47 -0800, corey escreveu:

**Comment by coooooooorey** [comment]
ok. thanks.
